### ISSUE TITLE
Submit to OpenLDAP as a contribution

### ISSUE THREAD

**Issue by quanah** [wclarie/openldap-bcrypt#1]
Hi,

Would you be willing to submit this upstream to OpenLDAP so it can be included as one of its contrib modules, similar to what has been done with SSHA2 support and TOTP contrib modules, etc?

The [ITS system](http://www.openldap.org/its) should be used to submit, and see the [contribution guidelines](http://www.openldap.org/devel/contributing.html)

Thanks!

**Comment by quanah** [comment]
Hi, just wanted to ping and see if you've had time to consider this.  Thanks!

**Comment by detrout** [comment]
The license in all the source files says "public domain". Could someone else submit it to openldap?

**Comment by wclarie** [comment]
You're welcome to fork and/or submit it as you please. I do not use OpenLDAP anymore so I cannot test or maintain this.

**Comment by quanah** [comment]
Third party submissions to the OpenLDAP project are not allowed, so no, no one else can submit it.

@wclarie if you submit it to the OpenLDAP project, then the project can take over maintaining the overlay.

**Comment by quanah** [comment]
@wclarie ping? ;)

**Comment by quanah** [comment]
@wclarie ping? :)  Would be nice to get this officially into openldap

**Comment by quanah** [comment]
@wclarie Ping?  Can we please move forward on this?

**Comment by ponahoum** [comment]
I agree ! would to totally have that in OpenLdap !

**Comment by quanah** [comment]
@wclarie Ping? Can this please be done? :)

**Comment by nxg** [comment]
I'd like to ditto @quanah.  I'd love to use this module, but it would give me a very warm glow to get it via the OpenLDAP distribution rather than via a separate repo (which can of course disappear, go funny, and generally not be something one would bet the farm on).

If I'm reading the [contribution guidance](https://www.openldap.org/devel/contributing.html) correctly, it looks like ‘submitting’, in this particular case, would be no more burdensome than opening a ticket and saying 'please take this off my hands `<Github URL>`'.  Perhaps Qanah can confirm.

**Comment by quanah** [comment]
That's mostly correct.  All that is needed is to open an ITS at http://www.openldap.org/its stating the desire to contribute the code back to the project, the link to where we can obtain the code (this github repo), and an IPR statement (https://www.openldap.org/devel/contributing.html#notice), and I'll take it from there.

The crucial part is the IPR statement as noted at https://www.openldap.org/devel/contributing.html#n-contrib

An example from a previous slapd module being contributed can be found at https://www.openldap.org/its/index.cgi/?findid=7742

There is no burden on @wclarie to maintain this module once it is contributed.

**Comment by ser** [comment]
via https://en.wikipedia.org/wiki/Unlicense

The Free Software Foundation states that "Both public domain works and the lax license provided by the Unlicense are compatible with the GNU GPL."

**Comment by quanah** [comment]
> 
> 
> via https://en.wikipedia.org/wiki/Unlicense
> 
> The Free Software Foundation states that "Both public domain works and the lax license provided by the Unlicense are compatible with the GNU GPL."

What does that have to do with anything being discussed here?

**Comment by ser** [comment]
That the current license allows to be changed to whatever we want, including OpenLDAP license. 

Moreover, my friend has just contacted the author, who is not using OpenLDAP anymore and he permitted to include it into OpenLDAP as whoever we want / need.

There are no obstacles now, the situation is clear.

**Comment by quanah** [comment]
> 
> 
> That the current license allows to be changed to whatever we want, including OpenLDAP license.
> 
> Moreover, my friend has just contacted the author, who is not using OpenLDAP anymore and he permitted to include it into OpenLDAP as whoever we want / need.
> 
> There are no obstacles now, the situation is clear.

Great, so the author simply needs to do what I've asked him to do for over 2 years.  

a) Open an ITS at http://www.openldap.org/its

b) Provide an IPR: https://www.openldap.org/devel/contributing.html#notice

Again, the issue isn't the LICENSE it's about the original author properly assigning their rights over to the OpenLDAP project,

**Comment by quanah** [comment]
In part, it is important from the OpenLDAP project side, to have the ITS filed, so that the project has a historical record of the rights assignment, etc.  3rd party "verbal" approval is not something we are able to work with.

**Comment by ser** [comment]
You can't ask anyone to do what they don't want to do. Author cedes his rights to anyone who volunteers to submit. It is not a verbal approval, it's a written approval.

**Comment by quanah** [comment]
> 
> 
> You can't ask anyone to do what they don't want to do. Author cedes his rights to anyone who volunteers to submit. It is not a verbal approval, it's a written approval.

a) They've never stated they have an issue with the rights assignment.  I'm simply noting that it's required for this module to be contributed back to openldap

b) There is no approval, written, verbal, or otherwise, directly from the author, in the OpenLDAP ITS system, which is the only place in which approval matters as far as being a contribution.  Until/unless the author is able to do this, the project cannot move anywhere on this.

**Comment by ser** [comment]
If you plan to just wait here forever, it won't happen. Write the author, his email is in commits. He replied in less than hour.

**Comment by detrout** [comment]
As an aside what do you all think of using https://github.com/besser82/libxcrypt instead of another copy pasted version of crypt-bcrypt.c / crypt_blowfish.c?

(At some point I'd been looking to see if there was a a library in Debian that had an implementation of blowfish.)

**Comment by quanah** [comment]
@detrout Really the best thing would be to use an argon2 based module (See https://www.openldap.org/its/index.cgi/?findid=8575 for example)

**Comment by detrout** [comment]
That thread seems to implythat argon2 is a new password hashing algorithm and not a library of hashing algorithms. 

libxcrypt is a library and it looks like it has implementations of scrypt, PBKDF1, and bcrypt, designed to return $code$hash  crypt compatible values.

I thought this thread started out as an attempt to get openldap to support bcrypt.

**Comment by quanah** [comment]
>
> I thought this thread started out as an attempt to get openldap to support bcrypt.

This thread is about getting this very specific overlay contributed to the OpenLDAP project, so that it can be distributed with the OpenLDAP source code as other modules that extend LDAP functionality past the RFCs is done.  If you want to start a general thread about hashing libraries, etc, then the OpenLDAP technical list would be the best location for that.

I would note that generally OpenLDAP is looking for code items that are portable with a minimum of external dependencies.

In the argon2 case, libsodium would likely be the appropriate library for an argon2 module, as is discussed in the above referenced ITS.

**Comment by quanah** [comment]
> 
> 
> If you plan to just wait here forever, it won't happen. Write the author, his email is in commits. He replied in less than hour.

Updating this issue sends the author an email.  Pinging the author directly as was done multiple times sends the author an email.   Note that the author has previously replied to this issue.  The lack of response from the author generally indicates to me a lack of interest in contributing this module, regardless of what anyone else has to say.

Given the complete lack of interest by the author for over 3 years, I'm going to go ahead and close this.

**Comment by ser** [comment]
Funny, blaming the author if the author agreed several times to include this module, just nobody wants to help him.
